version: 2

models:
  - name: stg_orders
    description: "Cleaned and standardized orders from raw source"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - unique
          - not_null

      - name: customer_id
        description: "ID of the customer who placed the order"
        tests:
          - not_null

      - name: status
        description: "Current status of the order"
        tests:
          - not_null
          - accepted_values:
             arguments:
              values: ['completed', 'pending', 'cancelled']
          

      - name: order_amount
        description: "Total amount of the order"
        tests:
          - not_null

  - name: stg_customers
    description: "Cleaned and standardized customers from raw source"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - unique
          - not_null

      - name: email
        description: "Customer email address"
        tests:
          - unique
          - not_null